### ISSUE TITLE
Verbose Mode

### ISSUE THREAD

**Issue by vrbrito** [Sebubu/hueyx#2]
Hello,

Could you clarify the use of verbose options?

Thank you in advance.

**Comment by Sebubu** [comment]
Which one do you mean?

**Comment by SeverinAlexB** [comment]
There is one verbose mode in the huey base package

```
-v, --verbose
Verbose logging (loglevel=DEBUG). If no logfile is specified and verbose is set, then the consumer will log to the console.
```

```
Due to a conflict with Django’s base option list, the “verbose” option is set using -V or --huey-verbose. When enabled, huey logs at the DEBUG level.
```

Have a look at https://huey.readthedocs.io/en/latest/consumer.html#consumer-options and https://huey.readthedocs.io/en/latest/contrib.html#setting-things-up.

**Comment by vrbrito** [comment]
That's it, thank you very much!
