### ISSUE TITLE
Event Listener

### ISSUE THREAD

**Issue by vrbrito** [Sebubu/hueyx#3]
Hello,

Could you help me to access the event listener using hueyx?

On native HUEY, I would have:

` HUEY = RedisHuey('general', always_eager=False) `

```
pubsub = settings.HUEY.storage.listener()

        for message in pubsub.listen():

                 ...
```

For the analogue HUEYX definition:

```
HUEYX = {'general': {
            'connection': {'connection_pool': ConnectionPool(host='localhost', port=6379, db=0)},
            'consumer': {'workers': 1, 'worker_type': 'thread'},
            'always_eager': False
        },
        'monitors': {
            'connection': {'connection_pool': ConnectionPool(host='localhost', port=6379, db=1, max_connections=20)},
            'consumer': {'workers': 10,'worker_type': 'thread'},
            'always_eager': False,
        },
}
```

How could I access the event listener?

Thank you in advance.

**Comment by SeverinAlexB** [comment]
You get your huey instance by 
```python
from hueyx.queues import hueyx

HUEY_GENERAL = hueyx('general')
HUEY_MONITORS = hueyx('monitors')
```

Then you should access the storage by
```python
storage = HUEY_GENERAL.storage
```
See https://huey.readthedocs.io/en/1.11.0/events.html#listening-to-events

Be aware, the huey base package replaced the event system by a signal system. Chances are that your code above is already deprecated. Hueyx itself is not tested yet with huey 2.0. See #4 .

**Comment by vrbrito** [comment]
Do you know how to combine both storages on a single listener?

**Comment by SeverinAlexB** [comment]
With a hack yes. Have a look at the huey exporter 
https://github.com/APGSGA/huey-exporter/blob/master/huey_exporter/EventListener.py#L102

It provides Prometheus metrics and explores/subscribes queues automatically.

**Comment by vrbrito** [comment]
Thank you very much, @Sebubu

**Comment by SeverinAlexB** [comment]
Hueyx 1.0.0 has been released. The signal system is now supported.
